stdp_test = {
'save_df': True,
'save_logs': True,
'save_fb_values': True,
'tmax_di': 100,
'tmax_di_fb': 100,
'stdp_samples': 1,
'surprise_shuffle': True,
}

config_collection = {
'stdp_test': stdp_test,
}

result_keys = [
'loss_test',
'loss_train',
'acc_test',
'acc_train',
'fb_values',
'fb_values_network',
]

statistics_keys = [
'loss_test_val_best',
'loss_test_best',
'loss_train_best',
'loss_val_best',
'loss_test_last',
'loss_train_last',
'loss_val_last',
]

config_fixed = {
'epochs': 40,
'lr': 0.005471651731803144,
'alpha_di': 4.2965664865826373e-07,
'sigma': 0.004608554873393829,
'sigma_output': 0.03511750971092282,
'epsilon': 2.0317675095402725e-07,
'time_constant_ratio': 0.049781046616406664,
'beta1': 0.9,
'beta2': 0.9,
'decay_rate': 0.8487886243637842,
'target_class_value': 1.0,
'low_pass_filter_u': True,
'dataset': 'mnist',
'num_train': 1000,
'num_test': 1000,
'num_val': 1000,
'no_preprocessing_mnist': False,
'no_val_set': False,
'batch_size': 128,
'lr_fb': 0.1,
'lr_fb_init': 0.1,
'target_stepsize': 0.001,
'optimizer': 'Adam',
'optimizer_fb': 'Adam',
'momentum': 0.0,
'forward_wd': 0,
'feedback_wd': 0,
'train_parallel': False,
'normalize_lr': False,
'epochs_fb': 0,
'freeze_forward_weights': False,
'freeze_fb_weights': True,
'freeze_fb_weights_output': True,
'shallow_training': False,
'extra_fb_epochs': 0,
'extra_fb_minibatches': 0,
'only_train_first_layer': False,
'train_only_feedback_parameters': False,
'clip_grad_norm': 1.0,
'grad_deltav_cont': True,
'beta1_fb': 0.99,
'beta2_fb': 0.99,
'epsilon_fb': 1e-08,
'num_hidden': 3,
'size_hidden': 256,
'size_input': 784,
'size_output': 10,
'hidden_activation': 'sigmoid',
'output_activation': 'softmax',
'no_bias': False,
'network_type': 'DFC_single_phase',
'initialization': 'xavier_normal',
'fb_activation': 'sigmoid',
'no_cuda': False,
'random_seed': 42,
'cuda_deterministic': False,
'hpsearch': False,
'multiple_hpsearch': False,
'single_precision': False,
'evaluate': False,
'out_dir': None,
'save_lu_loss': False,
'save_LU_angle': False,
'at_steady_state': False,
'save_BP_angle': False,
'save_GN_angle': False,
'save_GNT_angle': False,
'save_condition_gn': False,
'gn_damping': 0.0,
'log_interval': 1,
'gn_damping_hpsearch': False,
'save_nullspace_norm_ratio': False,
'save_fb_statistics_init': False,
'compute_gn_condition_init': False,
'ndi': False,
'dt_di': 0.001,
'dt_di_fb': 0.001,
'epsilon_di': 0.5,
'reset_K': False,
'initialization_K': 'xavier_normal',
'noise_K': 0.0,
'compare_with_ndi': False,
'learning_rule': 'nonlinear_difference',
'use_initial_activations': False,
'k_p': 2.0,
'k_p_fb': 0.0,
'inst_system_dynamics': False,
'alpha_fb': 0.5,
'noisy_dynamics': False,
'fb_learning_rule': 'normal_controller',
'inst_transmission': True,
'inst_transmission_fb': True,
'time_constant_ratio_fb': 0.005,
'apical_time_constant': -1,
'apical_time_constant_fb': 0.5,
'efficient_controller': False,
'proactive_controller': True,
'simulate_layerwise': True,
'scaling_fb_updates': True,
'stability_tricks': False,
'pretrain_without_controller': False,
'error_as_loss_grad': True,
'tau_f': 0.5,
'tau_noise': 0.05,
'inst_system_dynamics_fb': False,
'include_non_converged_samples': True,
'sum_reduction': True,
'save_stdp_measures': True,
'use_diff_hebbian_updates': True,
'use_stdp_updates': False,
'save_checkpoints': False,
'save_correlations': False,
'use_jacobian_as_fb': True,
}